# Generated by Django 3.1.3 on 2021-01-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Encaminhado', 'Encaminhado'), ('Entregue', 'Entregue')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Estoque', 'Estoque'), ('Fora do estoque', 'Fora do estoque')], max_length=200, null=True),
        ),
    ]
