# Generated by Django 3.1.3 on 2021-01-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20210130_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Encaminhado', 'Encaminhado'), ('Entregue', 'Entregue')], max_length=200, null=True),
        ),
    ]
